"""Install an auto-loading ``instrmcp`` Jupyter kernelspec.

This is the heart of the "one start action" experience (PRD Option A): any notebook
opened on the ``instrmcp`` kernel automatically loads the IPython extension, sets the
configured mode/options, and starts the kernel-hosted MCP server — no manual
``%load_ext`` / ``%mcp_start`` ritual.

Mechanism: the generated ``kernel.json`` passes
``--IPKernelApp.exec_files={resource_dir}/instrmcp_startup.py`` to ipykernel. Jupyter
substitutes ``{resource_dir}`` with the installed kernelspec directory at launch time,
so the startup script runs before the user's first cell. ``exec_files`` (a single path)
sidesteps the unreliable list-valued ``--IPKernelApp.exec_lines`` CLI parsing.

The startup script invokes the existing magics (``%load_ext instrmcp.extensions``,
``%mcp_safe/unsafe/dangerous``, ``%mcp_option add ...``, ``%mcp_start``), so this never
duplicates server-start logic — it drives the exact path users run by hand today.
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
import warnings
from pathlib import Path
from typing import Optional

from instrmcp.app.profiles import Profile
from instrmcp.utils.logging_config import get_logger

logger = get_logger("app.install_kernel")

_MODE_MAGIC = {
    "safe": "mcp_safe",
    "unsafe": "mcp_unsafe",
    "dangerous": "mcp_dangerous",
}


def _startup_script(profile: Profile) -> str:
    """Generate the IPython startup script that auto-starts the MCP server.

    The script is run via ``--IPKernelApp.exec_files`` during kernel init. To avoid
    blocking the kernel's readiness handshake (importing qcodes/measureit + starting
    uvicorn can take tens of seconds, which makes JupyterLab time out and *restart*
    the kernel), the actual work is **deferred** onto the kernel's event loop with
    ``call_later`` so init_code returns immediately and the kernel reports ready. All
    steps are wrapped defensively so a failure (e.g. port already in use) prints a
    message instead of crashing the kernel into a restart loop.
    """
    mode_magic = _MODE_MAGIC.get(profile.mcp.mode, "mcp_safe")

    magic_calls = ["        ip.run_line_magic('load_ext', 'instrmcp.extensions')"]
    magic_calls.append(f"        ip.run_line_magic('{mode_magic}', '')")
    for opt in profile.mcp.options:
        magic_calls.append(f"        ip.run_line_magic('mcp_option', 'add {opt}')")
    if profile.mcp.autostart:
        magic_calls.append("        ip.run_line_magic('mcp_start', '')")
    body = "\n".join(magic_calls)

    return f"""# Auto-generated by `instrmcp install-kernel`. Do not edit by hand.
# Regenerate after changing a profile's mcp.mode / mcp.options.


def _instrmcp_autostart():
    from IPython import get_ipython

    ip = get_ipython()
    if ip is None:
        return
    try:
{body}
    except Exception as exc:  # never crash the kernel on auto-start failure
        print(f"[instrmcp] auto-start failed: {{exc}}")
        print("[instrmcp] You can start it manually: %load_ext instrmcp.extensions; %mcp_start")


# Defer onto the kernel event loop so init does not block kernel readiness
# (a slow synchronous import here would make JupyterLab restart the kernel).
try:
    import asyncio

    asyncio.get_event_loop().call_later(0.5, _instrmcp_autostart)
except Exception:
    _instrmcp_autostart()
"""


def _kernel_json(profile: Profile) -> dict:
    """Build the kernel.json contents for the instrmcp kernelspec."""
    return {
        "argv": [
            sys.executable,
            "-m",
            "ipykernel_launcher",
            "-f",
            "{connection_file}",
            "--IPKernelApp.exec_files={resource_dir}/instrmcp_startup.py",
        ],
        "display_name": f"Python 3 (instrmcp · {profile.mcp.mode})",
        "language": "python",
        "metadata": {
            "instrmcp": {
                "profile": profile.name,
                "mode": profile.mcp.mode,
                "options": sorted(profile.mcp.options),
                "autostart": profile.mcp.autostart,
            }
        },
    }


def install_kernel(profile: Profile, replace: bool = True) -> Path:
    """Install the ``instrmcp`` kernelspec for the current user.

    Args:
        profile: Profile whose mcp.mode/options/autostart are baked into the startup
            script and recorded in kernel.json metadata.
        replace: Overwrite an existing kernelspec of the same name.

    Returns:
        The installed kernelspec resource directory.
    """
    from jupyter_client.kernelspec import KernelSpecManager

    kernel_name = profile.jupyter.kernel_name

    with tempfile.TemporaryDirectory() as tmp:
        source_dir = Path(tmp)
        (source_dir / "kernel.json").write_text(
            json.dumps(_kernel_json(profile), indent=2) + "\n"
        )
        (source_dir / "instrmcp_startup.py").write_text(_startup_script(profile))

        ksm = KernelSpecManager()
        # `replace` is required on old jupyter_client to overwrite, but newer
        # versions always replace and emit a DeprecationWarning if it's passed.
        # Pass it for compatibility but suppress the noise on newer versions.
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", DeprecationWarning)
            ksm.install_kernel_spec(
                str(source_dir),
                kernel_name=kernel_name,
                user=True,
                replace=replace,
            )

    resource_dir = Path(ksm.get_kernel_spec(kernel_name).resource_dir)
    logger.info("Installed kernelspec '%s' at %s", kernel_name, resource_dir)
    return resource_dir


def uninstall_kernel(kernel_name: str = "instrmcp") -> bool:
    """Remove the ``instrmcp`` kernelspec. Returns True if something was removed."""
    from jupyter_client.kernelspec import KernelSpecManager, NoSuchKernel

    ksm = KernelSpecManager()
    try:
        spec = ksm.get_kernel_spec(kernel_name)
    except NoSuchKernel:
        return False
    shutil.rmtree(spec.resource_dir, ignore_errors=True)
    logger.info("Removed kernelspec '%s' at %s", kernel_name, spec.resource_dir)
    return True


def kernel_installed(kernel_name: str = "instrmcp") -> bool:
    """Return True if the named kernelspec is installed."""
    from jupyter_client.kernelspec import KernelSpecManager

    return kernel_name in KernelSpecManager().find_kernel_specs()


def installed_kernel_metadata(kernel_name: str = "instrmcp") -> Optional[dict]:
    """Return the ``metadata.instrmcp`` block of the installed kernelspec, if any."""
    from jupyter_client.kernelspec import KernelSpecManager, NoSuchKernel

    ksm = KernelSpecManager()
    try:
        spec = ksm.get_kernel_spec(kernel_name)
    except NoSuchKernel:
        return None
    meta = getattr(spec, "metadata", None) or {}
    return meta.get("instrmcp")
